name: Pa11y

# From Adrian Bolonio's article: https://www.adrianbolonio.com/en/accessibility-github-actions/

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on http://localhost:3000
      - name: Run pa11y
        run: |
          npm install --location=global pa11y
          pa11y http://localhost:3000 --runner axe --runner htmlcs --threshold 10
